backend:
  name: git-gateway
  branch: master
  # name: test-repo
media_folder: public/images
public_folder: /images

collections:
  - name: "config"
    label: "Config"
    delete: false
    editor:
      preview: false
    files:
      - name: "general"
        label: "Site Config"
        file: "config.json"
        description: "General site settings"
        fields:
          - label: "URL"
            name: "base_url"
            widget: "string"
            hint: "Do not enter the trailing slash of the URL"
          - label: "Site title"
            name: "site_title"
            widget: "string"
          - label: "Site description"
            name: "site_description"
            widget: "string"
          - label: "Site keywords"
            name: "site_keywords"
            widget: "list"
            summary: "{{fields.keyword.keyword}}"
            field:
              label: Keyword
              name: keyword
              widget: "string"
          - label: "Twitter account"
            name: "twitter_account"
            widget: "string"
          - label: "GitHub account"
            name: "github_account"
            widget: "string"

  - name: "meta"
    label: "Meta"
    delete: false
    editor:
      preview: false
    files:
      - name: "authors"
        label: "Authors"
        file: "meta/authors.yml"
        description: "Author descriptions"
        fields:
          - name: authors
            label: Authors
            label_singular: "Author"
            widget: list
            fields:
              - label: "Slug"
                name: "slug"
                widget: "string"
                hint: "The part of a URL identifies the author"
              - label: "Name"
                name: "name"
                widget: "string"
                hint: "First and Last"
              - label: "Introduction"
                name: "introduction"
                widget: "text"
      - name: "tags"
        label: "Tags"
        file: "meta/tags.yml"
        description: "List of tags"
        fields:
          - name: tags
            label: Tags
            label_singular: "Tag"
            widget: list
            fields:
              - label: "Slug"
                name: "slug"
                widget: "string"
                hint: "The part of a URL identifies the tag"
              - label: "Display Name"
                name: "name"
                widget: "string"
                hint: "Tag name for displaying on the site"

  - name: "blog-basic"
    label: "Blog (Basic)"
    folder: "content/blogs/"
    extension: "mdx"
    format: "frontmatter"
    create: true
    slug: "{{date}}_{{heading}}"
    identifier_field: slug
    summary: "{{heading}}"
    fields:
      - { name: 'date', label: 'Publish Date', widget: 'datetime', format: 'YYYY-MM-DD', timeFormat: false }
      - { name: 'color', label: 'Color', widget: 'color', enableAlpha: true }
      - { name: 'hero_img_dt', label: 'Hero Image Desktop', widget: 'image' }
      - { name: 'hero_img_tb', label: 'Hero Image Tablet', widget: 'image' }
      - { name: 'hero_img_mb', label: 'Hero Image Mobile', widget: 'image' }
      - name: "tags"
        label: Tags
        label_singular: "Tag"
        widget: list
        summary: "{{fields.tag}}"
        field:
          label: Tag
          name: tag
          widget: relation
          collection: "meta"
          file: "tags"
          searchFields:
            - "tags.*.name"
          displayFields:
            - "tags.*.name"
          valueField: "tags.*.slug"
      - { name: 'heading', label: 'Heading', widget: 'string' }
      - { name: 'byline', label: 'Byline', widget: 'string' }
      - name: "body_list"
        label: "Body"
        widget: "list"
        field:
          label: "Section"
          name: "section"
          widget: "markdown"
